Repository novoda/download-manager, pull requests merged in 2018-06, with the labels that each got.

#396 DownloadError message
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatus.java
  library/src/main/java/com/novoda/downloadmanager/DownloadError.java
  library/src/main/java/com/novoda/downloadmanager/DownloadErrorFactory.java
  library/src/main/java/com/novoda/downloadmanager/DownloadFile.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/FileDownloader.java
  library/src/main/java/com/novoda/downloadmanager/InternalDownloadFileStatus.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadBatchStatus.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadFileStatus.java
  library/src/main/java/com/novoda/downloadmanager/NetworkFileDownloader.java
  library/src/test/java/com/novoda/downloadmanager/InternalDownloadBatchStatusFixtures.java
  library/src/test/java/com/novoda/downloadmanager/NetworkFileDownloaderTest.java
Labels: enhancement, v2

#395 Alternative migration complete
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/CustomDownloadsPersistence.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MigrationJob.java
  library/src/main/AndroidManifest.xml
  library/src/main/java/com/novoda/downloadmanager/CompletedDownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/CompletedDownloadBatchesExtractor.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigrator.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigratorBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersistence.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchStatusPersistence.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsPersistence.java
  library/src/main/java/com/novoda/downloadmanager/FileSizeExtractor.java
  library/src/main/java/com/novoda/downloadmanager/InternalMigrationStatus.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerCommands.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrator.java
  library/src/main/java/com/novoda/downloadmanager/MigrationCallback.java
  library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
  library/src/main/java/com/novoda/downloadmanager/MigrationStatus.java
  library/src/main/java/com/novoda/downloadmanager/MigrationStatusNotificationCreator.java
  library/src/main/java/com/novoda/downloadmanager/PartialDownloadBatchesExtractor.java
  library/src/main/java/com/novoda/downloadmanager/RoomDownloadsPersistence.java
  library/src/main/java/com/novoda/downloadmanager/VersionOneToVersionTwoMigrationStatus.java
  library/src/test/java/com/novoda/downloadmanager/CompletedDownloadBatchesExtractorTest.java
  library/src/test/java/com/novoda/downloadmanager/FakeDownloadsPersistence.java
Labels: v2

#397 Return Error not Type
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatus.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadBatchStatus.java
  library/src/test/java/com/novoda/downloadmanager/InternalDownloadBatchStatusFixtures.java
Labels: enhancement

#398 Check for the type of connected service
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
Labels: bug, v2

#399 Migration binder casting
  library/build.gradle
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigratorBuilder.java
Labels: bug, v2

#400 Move Migration code to demo package
  demo-simple/build.gradle
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/CompletedDownloadBatchesExtractor.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationJob.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationPathExtractor.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationStoragePathSanitizer.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/PartialDownloadBatchesExtractor.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/VersionOnePartialDownloadBatch.java
  demo-simple/src/test/java/com/novoda/downloadmanager/demo/migration/CompletedDownloadBatchesExtractorTest.java
  demo-simple/src/test/java/com/novoda/downloadmanager/demo/migration/MigrationPathExtractorTest.java
  demo-simple/src/test/java/com/novoda/downloadmanager/demo/migration/MigrationStoragePathSanitizerTest.java
  demo-simple/src/test/java/com/novoda/downloadmanager/demo/migration/StubCursor.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchTitleCreator.java
  library/src/main/java/com/novoda/downloadmanager/FilePathCreator.java
  library/src/main/java/com/novoda/downloadmanager/FileSizeCreator.java
  library/src/main/java/com/novoda/downloadmanager/FileSizeExtractor.java
  library/src/test/java/com/novoda/downloadmanager/FilePathCreatorTest.java
Labels: v2

#403 V2 alternative migration (worker thread)
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationJob.java
  library/src/main/java/com/novoda/downloadmanager/CompletedDownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersistence.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchStatusPersistence.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerCommands.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
Labels: enhancement, v2

#409 Use UUID in place of system.nanoTime.
  library/src/main/java/com/novoda/downloadmanager/RoomDownloadsPersistence.java
Labels: bug, v2

#410 CallbackThrottle & delete on error
  library/src/main/java/com/novoda/downloadmanager/CallbackThrottleByProgressIncrease.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/test/java/com/novoda/downloadmanager/CallbackThrottleByProgressIncreaseTest.java
Labels: bug, enhancement

#412 v2 Update dependencies
  library/build.gradle
Labels: enhancement, v2

#411 Path based persistence
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/CustomFilePersistence.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  library/src/main/java/com/novoda/downloadmanager/Batch.java
  library/src/main/java/com/novoda/downloadmanager/BatchFile.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchFactory.java
  library/src/main/java/com/novoda/downloadmanager/DownloadError.java
  library/src/main/java/com/novoda/downloadmanager/DownloadErrorFactory.java
  library/src/main/java/com/novoda/downloadmanager/DownloadFile.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersistence.java
  library/src/main/java/com/novoda/downloadmanager/ExternalFilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/FilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/FilePersistenceCreator.java
  library/src/main/java/com/novoda/downloadmanager/FilePersistenceType.java
  library/src/main/java/com/novoda/downloadmanager/LiteBatchBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteBatchFileBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerCommands.java
  library/src/main/java/com/novoda/downloadmanager/MigrationExtractor.java
  library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
  library/src/main/java/com/novoda/downloadmanager/PartialDownloadMigrationExtractor.java
  library/src/main/java/com/novoda/downloadmanager/PathBasedFilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/PrimaryStorageDownloadsDirectoryRoot.java
  library/src/main/java/com/novoda/downloadmanager/RoomAppDatabase.java
  library/src/main/java/com/novoda/downloadmanager/StorageRoot.java
  library/src/main/java/com/novoda/downloadmanager/StorageRootFactory.java
  library/src/test/java/com/novoda/downloadmanager/BatchBuilderTest.java
  library/src/test/java/com/novoda/downloadmanager/DownloadManagerTest.java
  library/src/test/java/com/novoda/downloadmanager/FilePersistenceFixtures.java
  library/src/test/java/com/novoda/downloadmanager/MigrationExtractorTest.java
  library/src/test/java/com/novoda/downloadmanager/TestStorageRootFactory.java
Labels: enhancement, v2
