Repository novoda/download-manager, pull requests merged in 2018-07, with the labels that each got.

#413 Concurrent modification exception
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/test/java/com/novoda/downloadmanager/DownloadManagerTest.java
Labels: bug, v2

#415 Multiple events
  library/src/main/java/com/novoda/downloadmanager/CallbackThrottleByProgressIncrease.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatusFilter.java
  library/src/main/java/com/novoda/downloadmanager/DownloadError.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/test/java/com/novoda/downloadmanager/CallbackThrottleByProgressIncreaseTest.java
  library/src/test/java/com/novoda/downloadmanager/DownloadBatchStatusFilterTest.java
  library/src/test/java/com/novoda/downloadmanager/InternalDownloadBatchStatusFixtures.java
Labels: v2

#416 Callback throttle rename
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/CustomFileCallbackThrottle.java
  library/src/main/java/com/novoda/downloadmanager/CallbackThrottle.java
  library/src/main/java/com/novoda/downloadmanager/CallbackThrottleCreator.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchFactory.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersistence.java
  library/src/main/java/com/novoda/downloadmanager/FileCallbackThrottle.java
  library/src/main/java/com/novoda/downloadmanager/FileCallbackThrottleByProgressIncrease.java
  library/src/main/java/com/novoda/downloadmanager/FileCallbackThrottleByTime.java
  library/src/test/java/com/novoda/downloadmanager/FileCallbackThrottleByProgressIncreaseTest.java
  library/src/test/java/com/novoda/downloadmanager/FileCallbackThrottleByTimeTest.java
  library/src/test/java/com/novoda/downloadmanager/FileCallbackThrottleCreatorTest.java
  library/src/test/java/com/novoda/downloadmanager/TestNonInstantiableCustomThrottle.java
  library/src/test/java/com/novoda/downloadmanager/TestNonPublicCustomThrottle.java
  library/src/test/java/com/novoda/downloadmanager/TestValidCustomThrottle.java
Labels: v2

#418 Add Storage Root to Batch
  library/roomSchemas/com.novoda.downloadmanager.RoomAppDatabase/3.json
  library/src/main/java/com/novoda/downloadmanager/Batch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchFactory.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatus.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersisted.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersistence.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadBatchStatus.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadsBatchPersisted.java
  library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
  library/src/main/java/com/novoda/downloadmanager/RoomAppDatabase.java
  library/src/main/java/com/novoda/downloadmanager/RoomBatch.java
  library/src/main/java/com/novoda/downloadmanager/RoomDownloadsPersistence.java
  library/src/test/java/com/novoda/downloadmanager/DownloadsBatchPersistedFixtures.java
  library/src/test/java/com/novoda/downloadmanager/InternalDownloadBatchStatusFixtures.java
Labels: enhancement, v2

#419 Fix timer task
  library/src/main/java/com/novoda/downloadmanager/FixedRateTimerActionScheduler.java
  library/src/test/java/com/novoda/downloadmanager/FixedRateTimerActionSchedulerTest.java
Labels: bug, v2

#420 Remove custom file persistence
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/CustomFilePersistence.java
  library/roomSchemas/com.novoda.downloadmanager.RoomAppDatabase/4.json
  library/src/main/java/com/novoda/downloadmanager/DownloadFile.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsFilePersisted.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsFilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/FilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/FilePersistenceCreator.java
  library/src/main/java/com/novoda/downloadmanager/FilePersistenceType.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadsFilePersisted.java
  library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
  library/src/main/java/com/novoda/downloadmanager/PathBasedFilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/RoomAppDatabase.java
  library/src/main/java/com/novoda/downloadmanager/RoomDownloadsPersistence.java
  library/src/main/java/com/novoda/downloadmanager/RoomFile.java
  library/src/test/java/com/novoda/downloadmanager/DownloadsFilePersistedFixtures.java
  library/src/test/java/com/novoda/downloadmanager/FilePersistenceFixtures.java
Labels: v2

#423 Migration create index crash
  library/build.gradle
  library/src/main/java/com/novoda/downloadmanager/RoomAppDatabase.java
Labels: v2
