Repository novoda/download-manager, pull requests merged in 2018-02, with the labels that each got.

#327 Notification removed on app start
  library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java
Labels: v2

#328 Notification dispatcher test failure
  library/src/test/java/com/novoda/downloadmanager/NotificationDispatcherTest.java
Labels: bug, v2

#329 319/custom notification channels
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/CustomNotificationCreatorFactory.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  library/src/main/java/com/novoda/downloadmanager/DefaultNotificationChannelProvider.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigratorBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrator.java
  library/src/main/java/com/novoda/downloadmanager/NotificationChannelProvider.java
  library/src/main/java/com/novoda/downloadmanager/NotificationCreator.java
  library/src/main/java/com/novoda/downloadmanager/OreoNotificationChannelProvider.java
Labels: v2

#330 Rename DELETION to DELETED
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatus.java
  library/src/main/java/com/novoda/downloadmanager/DownloadFile.java
  library/src/main/java/com/novoda/downloadmanager/DownloadFileStatus.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsFilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/InternalDownloadBatchStatus.java
  library/src/main/java/com/novoda/downloadmanager/InternalDownloadFileStatus.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadBatchStatus.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadFileStatus.java
  library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java
  library/src/test/java/com/novoda/downloadmanager/InternalDownloadBatchStatusFixtures.java
  library/src/test/java/com/novoda/downloadmanager/NotificationDispatcherTest.java
Labels: enhancement, v2

#331 Client specifies notification stackable or not
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  library/build.gradle
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigratorBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/NotificationCreator.java
  library/src/main/java/com/novoda/downloadmanager/NotificationCustomizer.java
  library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java
  library/src/main/java/com/novoda/downloadmanager/NotificationInformation.java
  library/src/test/java/com/novoda/downloadmanager/NotificationDispatcherTest.java
  library/src/test/java/com/novoda/downloadmanager/NotificationInformationFixtures.java
Labels: discussion, v2

#332 Generic NotificationDispatcher
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatusNotificationDispatcher.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java
  library/src/test/java/com/novoda/downloadmanager/DownloadBatchStatusNotificationDispatcherTest.java
  library/src/test/java/com/novoda/downloadmanager/NotificationDispatcherTest.java
Labels: v2

#333 Move notification display from service
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatusNotificationDispatcher.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerService.java
  library/src/main/java/com/novoda/downloadmanager/DownloadService.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadService.java
  library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java
  library/src/main/java/com/novoda/downloadmanager/ServiceNotificationDispatcher.java
  library/src/main/java/com/novoda/downloadmanager/ToWaitFor.java
  library/src/main/java/com/novoda/downloadmanager/Wait.java
  library/src/main/java/com/novoda/downloadmanager/WaitForDownloadService.java
  library/src/test/java/com/novoda/downloadmanager/DownloadBatchStatusNotificationDispatcherTest.java
  library/src/test/java/com/novoda/downloadmanager/NotificationDispatcherTest.java
  library/src/test/java/com/novoda/downloadmanager/ServiceNotificationDispatcherTest.java
  library/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: discussion, v2

#334 Duplicate files across batches
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchFactory.java
  library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
Labels: v2

#336 Align Services
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigrator.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigratorBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrator.java
  team-props/static-analysis.gradle
Labels: v2

#337 Hidden state
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigratorBuilder.java
  library/src/main/java/com/novoda/downloadmanager/NotificationCreator.java
  library/src/main/java/com/novoda/downloadmanager/NotificationCustomizer.java
  library/src/main/java/com/novoda/downloadmanager/NotificationInformation.java
  library/src/main/java/com/novoda/downloadmanager/ServiceNotificationDispatcher.java
  library/src/test/java/com/novoda/downloadmanager/NotificationInformationFixtures.java
  library/src/test/java/com/novoda/downloadmanager/ServiceNotificationDispatcherTest.java
Labels: v2

#338 Use file system for file size
  library/src/main/java/com/novoda/downloadmanager/MigrationExtractor.java
  library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
  library/src/test/java/com/novoda/downloadmanager/MigrationExtractorTest.java
Labels: v2

#339 Check whether a wakeLock is held before releasing
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadService.java
Labels: v2

#340 Expose downloads dir
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/ExternalFilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/InternalFilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerCommands.java
  library/src/main/java/com/novoda/downloadmanager/MigrationExtractor.java
  library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
Labels: v2

#341 On network error, not all scenarios recovers
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/NetworkFileDownloader.java
Labels: v2

#342 Use thread safe collections
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/test/java/com/novoda/downloadmanager/DownloadManagerTest.java
Labels: v2

#345 Stop service in case of hidden notification
  library/src/main/java/com/novoda/downloadmanager/ServiceNotificationDispatcher.java
  library/src/test/java/com/novoda/downloadmanager/ServiceNotificationDispatcherTest.java
Labels: v2

#346 Submit all stored downloads after migration completed
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  library/src/main/java/com/novoda/downloadmanager/AllStoredDownloadsSubmittedCallback.java
Labels: v2

#348 Use synchronized block for modifying the callback list
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/test/java/com/novoda/downloadmanager/DownloadManagerTest.java
Labels: v2

#349 Migration file ids
  demo-simple/src/main/assets/downloads.db
  library/src/main/java/com/novoda/downloadmanager/Migration.java
  library/src/main/java/com/novoda/downloadmanager/MigrationExtractor.java
  library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
  library/src/main/java/com/novoda/downloadmanager/PartialDownloadMigrationExtractor.java
  library/src/test/java/com/novoda/downloadmanager/MigrationExtractorTest.java
Labels: v2

#351 Fail fast when a file size request fails
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersistence.java
Labels: bug, v2

#353 Flashing notification on 4.4.2
  library/build.gradle
  library/src/main/java/com/novoda/downloadmanager/NotificationCreator.java
Labels: v2
