Repository novoda/download-manager, pull requests merged in 2018-09, with the labels that each got.

#417 Demo add storage root selection
  demo-simple/build.gradle
  demo-simple/src/main/AndroidManifest.xml
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/DownloadBatchStatusView.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/LandingActivity.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MigrationActivity.java
  demo-simple/src/main/res/layout/activity_landing.xml
  demo-simple/src/main/res/layout/activity_main.xml
  demo-simple/src/main/res/layout/activity_migration.xml
  demo-simple/src/main/res/layout/merge_download_batch_status.xml
  demo-simple/src/main/res/values/strings.xml
  library/build.gradle
  library/src/main/java/com/novoda/downloadmanager/DownloadFile.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
Labels: enhancement, v2

#404 Feature v2 alternative migration
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/CustomDownloadsPersistence.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MigrationActivity.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/PrimaryStoragePicturesDirectoryRoot.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/CompletedDownloadBatchesExtractor.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationJob.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationPathExtractor.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationStoragePathSanitizer.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/PartialDownloadBatchesExtractor.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/VersionOnePartialDownloadBatch.java
  demo-simple/src/test/java/com/novoda/downloadmanager/demo/migration/CompletedDownloadBatchesExtractorTest.java
  demo-simple/src/test/java/com/novoda/downloadmanager/demo/migration/MigrationPathExtractorTest.java
  demo-simple/src/test/java/com/novoda/downloadmanager/demo/migration/MigrationStoragePathSanitizerTest.java
  demo-simple/src/test/java/com/novoda/downloadmanager/demo/migration/StubCursor.java
  library/src/main/AndroidManifest.xml
  library/src/main/java/com/novoda/downloadmanager/CompletedDownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/CompletedDownloadFile.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchTitleCreator.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigrator.java
  library/src/main/java/com/novoda/downloadmanager/DownloadMigratorBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersistence.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchStatusPersistence.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsPersistence.java
  library/src/main/java/com/novoda/downloadmanager/FilePathCreator.java
  library/src/main/java/com/novoda/downloadmanager/FileSizeCreator.java
  library/src/main/java/com/novoda/downloadmanager/FileSizeExtractor.java
  library/src/main/java/com/novoda/downloadmanager/InternalMigrationStatus.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerCommands.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrationService.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrator.java
  library/src/main/java/com/novoda/downloadmanager/Migration.java
  library/src/main/java/com/novoda/downloadmanager/MigrationCallback.java
  library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
  library/src/main/java/com/novoda/downloadmanager/MigrationStatus.java
  library/src/main/java/com/novoda/downloadmanager/MigrationStatusNotificationCreator.java
  library/src/main/java/com/novoda/downloadmanager/RoomDownloadsPersistence.java
  library/src/main/java/com/novoda/downloadmanager/VersionOneToVersionTwoMigrationStatus.java
  library/src/main/res/values/strings.xml
  library/src/test/java/com/novoda/downloadmanager/FakeDownloadsPersistence.java
  library/src/test/java/com/novoda/downloadmanager/FilePathCreatorTest.java
  library/src/test/java/com/novoda/downloadmanager/MigrationExtractorTest.java
Labels: feature, v2

#424 Body length request
  library/build.gradle
  library/src/main/java/com/novoda/downloadmanager/NetworkFileSizeRequester.java
  library/src/test/java/com/novoda/downloadmanager/NetworkFileSizeRequesterTest.java
Labels: v2

#427 Rename lite download manager commands
  README.md
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/DemoApplication.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MigrationActivity.java
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/migration/MigrationJob.java
  library/src/main/java/com/novoda/downloadmanager/AllBatchStatusesCallback.java
  library/src/main/java/com/novoda/downloadmanager/AllStoredDownloadsSubmittedCallback.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatusCallback.java
  library/src/main/java/com/novoda/downloadmanager/DownloadFileStatusCallback.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsNetworkRecoveryCreator.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerCommands.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadsNetworkRecoveryEnabled.java
  library/src/main/java/com/novoda/downloadmanager/LiteJobCreator.java
  library/src/main/java/com/novoda/downloadmanager/LiteJobDownload.java
  library/src/test/java/com/novoda/downloadmanager/LiteDownloadManagerTest.java
Labels: :x: do-not-merge, v2

#407 V2 java doc
  demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
  demo-simple/src/main/res/xml/network_security_config.xml
  library/src/main/AndroidManifest.xml
  library/src/main/java/com/novoda/downloadmanager/AllBatchStatusesCallback.java
  library/src/main/java/com/novoda/downloadmanager/AllStoredDownloadsSubmittedCallback.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchId.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatus.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatusCallback.java
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchTitle.java
  library/src/main/java/com/novoda/downloadmanager/DownloadFileId.java
  library/src/main/java/com/novoda/downloadmanager/DownloadFileStatus.java
  library/src/main/java/com/novoda/downloadmanager/DownloadFileStatusCallback.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersisted.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersistence.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsFilePersisted.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsFilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/DownloadsPersistence.java
  library/src/main/java/com/novoda/downloadmanager/FileCallbackThrottle.java
  library/src/main/java/com/novoda/downloadmanager/FileDownloader.java
  library/src/main/java/com/novoda/downloadmanager/FilePath.java
  library/src/main/java/com/novoda/downloadmanager/FilePersistence.java
  library/src/main/java/com/novoda/downloadmanager/FileSize.java
  library/src/main/java/com/novoda/downloadmanager/FileSizeRequester.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerCommands.java
  library/src/main/java/com/novoda/downloadmanager/NotificationCustomizer.java
  library/src/main/java/com/novoda/downloadmanager/StorageRequirementRule.java
  library/src/main/java/com/novoda/downloadmanager/StorageRoot.java
  library/src/main/res/xml/network_security_config.xml
Labels: enhancement, v2

#430 Revert file size request fix
  build.gradle
  library/src/main/java/com/novoda/downloadmanager/NetworkFileSizeRequester.java
  library/src/test/java/com/novoda/downloadmanager/NetworkFileSizeRequesterTest.java
Labels: bug

#433 Wait.Then Holder
  library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatusNotificationDispatcher.java
  library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManager.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/main/java/com/novoda/downloadmanager/ServiceNotificationDispatcher.java
  library/src/main/java/com/novoda/downloadmanager/Wait.java
  library/src/test/java/com/novoda/downloadmanager/LiteDownloadManagerTest.java
  library/src/test/java/com/novoda/downloadmanager/ServiceNotificationDispatcherTest.java
Labels: bug
