Repository novoda/download-manager, pull requests merged in 2019-02, with the labels that each got.

#477 Add a single dismissible notification
  library/src/main/java/com/novoda/downloadmanager/NotificationCustomizer.java
  library/src/main/java/com/novoda/downloadmanager/ServiceNotificationDispatcher.java
Labels: enhancement

#478 DLM-472/Create BatchBuilder from Batch
  library/src/main/java/com/novoda/downloadmanager/BatchBuilder.java
Labels: enhancement

#480 Normalise paths when building BatchFile
  demo-simple/build.gradle
  library/build.gradle
  library/src/main/java/com/novoda/downloadmanager/LiteBatchFileBuilder.java
  library/src/test/java/com/novoda/downloadmanager/LiteBatchFileBuilderTest.java
Labels: bug

#479 DLM-253/Quick Returns
  library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
  library/src/main/java/com/novoda/downloadmanager/DownloadFile.java
  library/src/main/java/com/novoda/downloadmanager/FileCallbackThrottleByProgressIncrease.java
  library/src/main/java/com/novoda/downloadmanager/FileCallbackThrottleByTime.java
  library/src/main/java/com/novoda/downloadmanager/FixedRateTimerActionScheduler.java
  library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
  library/src/main/java/com/novoda/downloadmanager/PathBasedFilePersistence.java
  library/src/test/java/com/novoda/downloadmanager/FileCallbackThrottleByProgressIncreaseTest.java
  library/src/test/java/com/novoda/downloadmanager/FileCallbackThrottleByTimeTest.java
Labels: discussion, enhancement
